[workspace]
resolver = "3"
# Package names updated to "*-conflux"; workspace directories unchanged
members = [
    "aucpace",
    "spake2",
    "srp",
    "secret-utils",
]

[profile.dev]
opt-level = 2
